name: material_charts
description: "A flutter library for creating and manage industrial standard charts"
version: 0.0.15
homepage: https://github.com/vishnudas-bluefox/material_charts
repository: https://github.com/vishnudas-bluefox/material_charts

environment:
  sdk: ^3.5.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# flutter:

topics:
  - persistence
  - charts
  - graph
  - diagram
  - visualization
